variable env {}
variable host {}
variable database {}
variable user {}
variable password {}
variable port {}
variable psycopg2_arn {}
variable client_id {}
variable group_name_student {}
variable group_name_professor {}
variable user_pool_id {}
variable user_pool_arn {}
